//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="pl.bialystok.info", ConfigurationName="ServiceReference.Application")]
    public interface Application
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="add_event", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.add_eventResponse1> add_eventAsync(ServiceReference.add_event1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="get_events", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.get_eventsResponse1> get_eventsAsync(ServiceReference.get_events1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="get_pdf_report", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference.get_pdf_reportResponse1> get_pdf_reportAsync(ServiceReference.get_pdf_report1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pl.bialystok.info")]
    public partial class add_event
    {
        
        private string nameField;
        
        private string event_typeField;
        
        private string dateField;
        
        private string descriptionField;
        
        private byte[] image_dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string event_type
        {
            get
            {
                return this.event_typeField;
            }
            set
            {
                this.event_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=4)]
        public byte[] image_data
        {
            get
            {
                return this.image_dataField;
            }
            set
            {
                this.image_dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pl.bialystok.info")]
    public partial class get_pdf_reportResponse
    {
        
        private byte[] get_pdf_reportResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=0)]
        public byte[] get_pdf_reportResult
        {
            get
            {
                return this.get_pdf_reportResultField;
            }
            set
            {
                this.get_pdf_reportResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pl.bialystok.info")]
    public partial class get_pdf_report
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pl.bialystok.info")]
    public partial class get_eventsResponse
    {
        
        private string[] get_eventsResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public string[] get_eventsResult
        {
            get
            {
                return this.get_eventsResultField;
            }
            set
            {
                this.get_eventsResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pl.bialystok.info")]
    public partial class get_events
    {
        
        private string dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="pl.bialystok.info")]
    public partial class add_eventResponse
    {
        
        private string add_eventResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string add_eventResult
        {
            get
            {
                return this.add_eventResultField;
            }
            set
            {
                this.add_eventResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class add_event1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pl.bialystok.info", Order=0)]
        public ServiceReference.add_event add_event;
        
        public add_event1()
        {
        }
        
        public add_event1(ServiceReference.add_event add_event)
        {
            this.add_event = add_event;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class add_eventResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pl.bialystok.info", Order=0)]
        public ServiceReference.add_eventResponse add_eventResponse;
        
        public add_eventResponse1()
        {
        }
        
        public add_eventResponse1(ServiceReference.add_eventResponse add_eventResponse)
        {
            this.add_eventResponse = add_eventResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_events1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pl.bialystok.info", Order=0)]
        public ServiceReference.get_events get_events;
        
        public get_events1()
        {
        }
        
        public get_events1(ServiceReference.get_events get_events)
        {
            this.get_events = get_events;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_eventsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pl.bialystok.info", Order=0)]
        public ServiceReference.get_eventsResponse get_eventsResponse;
        
        public get_eventsResponse1()
        {
        }
        
        public get_eventsResponse1(ServiceReference.get_eventsResponse get_eventsResponse)
        {
            this.get_eventsResponse = get_eventsResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_pdf_report1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pl.bialystok.info", Order=0)]
        public ServiceReference.get_pdf_report get_pdf_report;
        
        public get_pdf_report1()
        {
        }
        
        public get_pdf_report1(ServiceReference.get_pdf_report get_pdf_report)
        {
            this.get_pdf_report = get_pdf_report;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_pdf_reportResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="pl.bialystok.info", Order=0)]
        public ServiceReference.get_pdf_reportResponse get_pdf_reportResponse;
        
        public get_pdf_reportResponse1()
        {
        }
        
        public get_pdf_reportResponse1(ServiceReference.get_pdf_reportResponse get_pdf_reportResponse)
        {
            this.get_pdf_reportResponse = get_pdf_reportResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ApplicationChannel : ServiceReference.Application, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ApplicationClient : System.ServiceModel.ClientBase<ServiceReference.Application>, ServiceReference.Application
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ApplicationClient() : 
                base(ApplicationClient.GetDefaultBinding(), ApplicationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Application.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), ApplicationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ApplicationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.add_eventResponse1> ServiceReference.Application.add_eventAsync(ServiceReference.add_event1 request)
        {
            return base.Channel.add_eventAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.add_eventResponse1> add_eventAsync(ServiceReference.add_event add_event)
        {
            ServiceReference.add_event1 inValue = new ServiceReference.add_event1();
            inValue.add_event = add_event;
            return ((ServiceReference.Application)(this)).add_eventAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.get_eventsResponse1> ServiceReference.Application.get_eventsAsync(ServiceReference.get_events1 request)
        {
            return base.Channel.get_eventsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.get_eventsResponse1> get_eventsAsync(ServiceReference.get_events get_events)
        {
            ServiceReference.get_events1 inValue = new ServiceReference.get_events1();
            inValue.get_events = get_events;
            return ((ServiceReference.Application)(this)).get_eventsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.get_pdf_reportResponse1> ServiceReference.Application.get_pdf_reportAsync(ServiceReference.get_pdf_report1 request)
        {
            return base.Channel.get_pdf_reportAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.get_pdf_reportResponse1> get_pdf_reportAsync(ServiceReference.get_pdf_report get_pdf_report)
        {
            ServiceReference.get_pdf_report1 inValue = new ServiceReference.get_pdf_report1();
            inValue.get_pdf_report = get_pdf_report;
            return ((ServiceReference.Application)(this)).get_pdf_reportAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Application))
            {
                return new System.ServiceModel.EndpointAddress("http://127.0.0.1:8000/");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ApplicationClient.GetBindingForEndpoint(EndpointConfiguration.Application);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ApplicationClient.GetEndpointAddress(EndpointConfiguration.Application);
        }
        
        public enum EndpointConfiguration
        {
            
            Application,
        }
    }
}
